{% set name = "rstream" %}
{% set version = "0.20.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rstream-{{ version }}.tar.gz
  sha256: 01d6f21926df8c04e90cac34a60a8906219bfbec5dc351ea5208056a96b8ddef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.31.0,<3.0.0
    - mmh3 >=4.0.0,<5.0.0
    - typing_extensions >=4.11.0,<5.0.0

test:
  imports:
    - rstream
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/rabbitmq-community/rstream
  summary: A python client for RabbitMQ Streams
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
